spring:
  application:
    name: user-center
  profiles:
    active: dev
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    # 和 JDBC 测试的 URL 完全一致
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}  # 确保和 JDBC 测试的密码一致

server:
  port: ${server.port}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
